### PR TITLE
Tomo's UI tweaks

### PR DESCRIPTION
**Pull request by CarlBeek**
Tomo has suggested some tweaks to the overall look to the Launchpad.

- [x] Increase button font to 16px and padding to 15px
- [x] Remove grey rectangle from ETH logo circles in Introduction section
- [x] Reduce box-shadow intensity to ɑ=0.3 on Overview page
- [x] Reduce the intensity of background colours on:
    - [x] Generate Keypairs page
    - [x] Upload deposit File page
    - [x] Connect Wallet page
- [x] Fix mismatched height on external links

I'm not sure how to reduce the intensity of the BG colours for the appropriate pages (when I edit what I thought were the RGB values, the result is not reflected where I'd expect), I'd appreciate help with this matter.

The desired change:
Screenshot 2020-07-20 at 5 40 28 PM

### CODE REVIEW

**Comment by georgeweiler** [comment]
I pushed the background color intensity changes. @CarlBeek let me know if you want to go even lighter with these

**Comment by georgeweiler** [comment]
Screen Shot 2020-07-20 at 9 58 56 AM
Screen Shot 2020-07-20 at 10 01 07 AM
Screen Shot 2020-07-20 at 9 55 48 AM

**Comment by CarlBeek** [comment]
Thanks for the help, @georgeweiler! I've implemented the exact colours as suggested by Tomo.

One last thing I'd like to tackle is the mismatched height between the arrow and the text on external links. Eg:

Screenshot 2020-07-20 at 7 49 40 PM

**Comment by georgeweiler** [comment]
I pushed a change that adds `withArrow` as a link prop, so we can have consistent styling for links with arrow icons.

**Comment by georgeweiler** [comment]
Screen Shot 2020-07-20 at 7 26 30 PM

**Comment by CarlBeek** [comment]
Those links are looking much better, thanks @georgeweiler.

Tomo asked for some further minor tweaks to the buttons which I just implemented (`font-size: 18px; letter-spacing: 1.5px;`).

I think this is ready for merge now. :)

**Pull request merged**
