### PR TITLE
Adds support for 10 new languages 🎉

### PR DESCRIPTION
**Pull request by wackerow**
## Description
Import of 8 new languages from Crowdin translations:

🎉 Arabic
🎉 Chinese Simplified
🎉 French
🎉 Greek
🎉 Indonesian
🎉 Korean
🎉 Portuguese Brazilian
🎉 Romanian
🎉 Italian
🎉 Japanese

Thank you to everyone who contributed!!

### Launchpad Translations Import Steps
- `LocatlizedRouter.tsx` - One time change, fixes to support 2 or 4-character lang code (ie, 'pt-br')
- Import `{lang}.json` files from Crowdin into `src/intl`
- Compile those (had to do each manually)
`formatjs compile src/intl/{lang}.json --format crowdin --out-file src/intl/compiled/{lang}.json --ast`
- Can then remove `src/intl/{lang}.json` files in lieu of `src/intl/compiled/{lang}.json`
- Add to `AppLanguage` enumerator in `src/intl/index.ts`
- Add to `langs` object within `Languages` component in `src/pages/Languages/index.tsx`

### CODE REVIEW

**Comment by wackerow** [comment]
Unfortunately noticed that the "acknowledgement" strings (ie. "The terminal", "Uptime", etc) were not tee'd up as translation strings. I added this in the last commit, which creates 5 new unique strings that will need to be added to Crowdin for translation.

**Review by samajammin — APPROVED** [review]
Nice work!

**Comment by wackerow** [comment]
Noted issue: Arabic text is not set up for right-to-left.

**Review by samajammin — APPROVED** [review]
🏆

**Pull request merged**
