### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rootulp**

### CODE REVIEW

**Review by wackerow — APPROVED** [review]
@rootulp Thanks! 👍🏻

**Comment by wackerow** [comment]
@samajammin This looks simple enough, but I thought about it more after approving... will this cause translations to break? If I recall, the english string is essentially hashed, and then it looks up the translation by that hash. In this case, that hash will now be different and it won't know which translated string to inject. If I'm correct we may need to update the reference to this string in the compiled intl files with the new hash.

**Review by samajammin — APPROVED** [review]
Thanks for the fix @rootulp!

Also nice catch to update the string hashes @wackerow 👍

**Comment by rootulp** [comment]
No problemo. Thanks for all your hard work maintaining this project @samajammin @wackerow

**Pull request merged**
