### PR TITLE
Adds checklist CTA to congrats page

### PR DESCRIPTION
**Pull request by georgeweiler**
Screen Shot 2020-10-13 at 5 07 43 PM

### CODE REVIEW

**Review by hwwhww — APPROVED** [review]
Thank you @georgeweiler! 👍 👍 
I pushed a commit for mirroring the latest https://github.com/eth2-clients/user-experience/blob/eth2-staker-checklist/eth2-staker-checklist.md. This PR looks good to me.

**Comment by hwwhww** [comment]
@georgeweiler Sorry! I just realized I should have committed on #206... please cherry-pick https://github.com/ethereum/eth2.0-deposit/pull/208/commits/81513c473f94ffcb2ccfc1cf56b0169d57a97700 to whatever branch you think the best. 🙏

**Review by Battenfield — APPROVED** [review]
🔥

**Comment by Battenfield** [comment]
I think it would be wise for us to change the Validator Clients Heading to "Review Validator Clients". This way there are not two competing calls to action. 

Another option would be to remove the validator clients from the Congrats page as it is already in a previous step and available in the nav and checklist.

Thoughts @CarlBeek @hwwhww?

**Pull request merged**
