### PR TITLE
Testnet clarification

### PR DESCRIPTION
**Pull request by CarlBeek**
This PR backpacks on the Env Var config to help further clarify the the difference between testnet & mainnet. This is achieved in the following ways:

* Header refers to `Eth2 Launch Pad for Altona testnet` instead of `Eth2 Launch Pad` when `IS_MAINNET` is false. As per @hwwhww's https://github.com/ethereum/eth2.0-deposit/pull/90#discussion_r449733093.
* All references to `ETH` are replaced with `GöETH`. (or whatever the appropriate ticker is (configurable from the envVar config)
* The Text in the top right has a clear background and `Altona` -> `Altona Testnet` as per https://github.com/ethereum/eth2.0-deposit/pull/90#issuecomment-653669745

### CODE REVIEW

**Comment by CarlBeek** [comment]
This currently targets the `testnet_clarification` branch, but can be changed to dev if #90 is merged.

**Comment by CarlBeek** [comment]
@Battenfield,can I ask you to take a look at this PR, please. I think fixes all of your concerns in #81

**Comment by Battenfield** [comment]
This is a very small stylistic nit: I'd prefer us to just have one instance of "Altona Testnet" in the Hero copy

Screen Shot 2020-07-09 at 10 31 09 PM

**Comment by Battenfield** [comment]
While QA-ing, I ran the current Launchpad CLI instructions for key generation and received this error:

Screen Shot 2020-07-09 at 10 46 32 PM

Is this a regression issue with the last Launchpad PR, or the CLI? @CarlBeek @hwwhww any ideas?

**Comment by hwwhww** [comment]
@Battenfield could you try to uninstall `eth2deposit` by: `pip3 uninstall eth2deposit` and then run `./deposit.sh install` again?

@CarlBeek we can fix it by bumping version in `setup.py`: https://github.com/ethereum/eth2.0-deposit-cli/blob/4ff0754aed188c6e240e93deb160d070ee656a05/setup.py#L9 for the new release.
I'll look into how to make our package dependencies better. 👀

**Comment by CarlBeek** [comment]
I agree that the duplication of "Altona testnet" was clunky, removed.

I've also adjusted the case on the rewards graph. Title Case looks much better than ALL CAPS.

**Comment by CarlBeek** [comment]
This PR is ready for review and merge.

**Pull request merged**
